Repository mayonnaise-workus/frontend, pull requests merged in 2023-03, with the labels that each got.

#4 마이페이지 화면 구현
  assets/images.ts
  assets/img/BookmarkSimple.png
  assets/img/ProfileImg2.png
  assets/img/pencil.png
  assets/img/profileImg.png
  assets/img/rightIcon.png
  src/components/login/mypage/Button/Button.tsx
  src/components/login/mypage/Button/style.ts
  src/components/login/mypage/Nickname/NickName.tsx
  src/components/login/mypage/Nickname/style.ts
  src/components/login/mypage/ScrapButton/ScrapButton.tsx
  src/components/login/mypage/ScrapButton/style.ts
  src/screens/MemberCancellationCompleteScreen/MemberCancellationCompleteScreen.tsx
  src/screens/MemberCancellationCompleteScreen/style.ts
  src/screens/MemberCancellationScreen/MemberCancellationScreen.tsx
  src/screens/MemberCancellationScreen/style.ts
  src/screens/MyPageScreen/MyPageScreen.tsx
  src/screens/MyPageScreen/style.ts
Labels: 🎨 Html&css

#5 마이페이지-로그아웃 기능, 닉네임 수정 기능, 스크랩 화면 구현
  assets/images.ts
  assets/img/BookmarkGray.png
  assets/img/DotsThreeOutlineVertical.png
  assets/img/X.png
  assets/img/logo.png
  src/App.tsx
  src/components/mypage/Button/Button.tsx
  src/components/mypage/Button/style.ts
  src/components/mypage/EditProfileFeature/EditProfileFeature.tsx
  src/components/mypage/EditProfileFeature/style.ts
  src/components/mypage/Header/Header.tsx
  src/components/mypage/Header/style.ts
  src/components/mypage/Nickname/NickName.tsx
  src/components/mypage/Nickname/style.ts
  src/components/mypage/ScrapButton/ScrapButton.tsx
  src/components/mypage/ScrapButton/style.ts
  src/components/mypage/ScrapHeader/ScrapHeader.tsx
  src/components/mypage/ScrapHeader/style.ts
  src/components/mypage/WorkSpaceList/WorkSpaceList.tsx
  src/components/mypage/WorkSpaceList/style.ts
  src/config/config.js
  src/data.js
  src/redux/service/EditNicknameApi.ts
  src/redux/service/Logout.ts
  src/redux/service/MemberApi.ts
  src/redux/service/WorkSpaceListApi.ts
  src/redux/slice/EditNicknameSlice.ts
  src/redux/slice/LogoutSlice.ts
  src/redux/slice/MemberSlice.ts
  src/redux/slice/WorkSpaceListSlice.ts
  src/redux/store/store.ts
  src/screens/EditProfileScreen/EditProfileScreen.tsx
  src/screens/EditProfileScreen/style.ts
  src/screens/MyPageScreen/MyPageScreen.tsx
  src/screens/ScrapScreen/ScrapScreen.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#6 코드 리뷰에 따른 리팩토링
  src/components/mypage/WorkSpaceList/WorkSpaceList.tsx
  src/redux/service/EditNicknameApi.ts
  src/redux/service/LoginApi.ts
  src/redux/service/PostNicknameApi.ts
  src/redux/service/PostPurposeApi.ts
  src/redux/service/PostRegionApi.ts
  src/redux/service/PostWorkSpaceApi.ts
  src/redux/service/ServiceTermApi.ts
  src/redux/service/auth-header.ts
  src/redux/slice/EditNicknameSlice.ts
  src/redux/slice/LoginSlice.ts
  src/redux/slice/LogoutSlice.ts
  src/redux/slice/MemberSlice.ts
  src/redux/slice/PostNicknameSlice.ts
  src/redux/slice/PostPurposeSlice.ts
  src/redux/slice/PostRegionSlice.ts
  src/redux/slice/PostWorkSpaceslice.ts
  src/redux/slice/ServiceTermSlice.ts
  src/redux/slice/WorkSpaceListSlice.ts
  src/redux/store/store.ts
  src/screens/EditProfileScreen/EditProfileScreen.tsx
  src/screens/MemberCancellationScreen/MemberCancellationScreen.tsx
  src/screens/OnboardingScreen/OnboardingScreen.tsx
  src/screens/RegisterNicknameScreen/RegisterNicknameScreen.tsx
  src/screens/RegisterPurposeScreen/RegisterPurposeScreen.tsx
  src/screens/RegisterRegionScreen/RegisterRegionScreen.tsx
  src/screens/RegisterWorkSpaceScreen/RegisterWorkSpaceScreen.tsx
  src/screens/ScrapScreen/ScrapScreen.tsx
  src/screens/ServiceTermScreen/ServiceTermScreen.tsx
Labels: 🔨 Refactor

#7 내비게이터 구조 전환 및 구글 로그인 기능 구현
  .eslintrc.js
  android/app/build.gradle
  android/app/debug.keystore
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  assets/images.ts
  assets/img/HomeIcon.png
  assets/img/MagazineIcon.png
  assets/img/MyIcon.png
  package-lock.json
  package.json
  src/App.tsx
  src/screens/HomeScreen/HomeScreen.tsx
  src/screens/IntroNavigator.tsx
  src/screens/MagazineScreen/MagazineScreen.tsx
  src/screens/MainNavigator.tsx
  src/screens/OnboardingScreen/OnboardingScreen.tsx
  src/screens/introScreenPropsType.ts
  src/screens/mainScreenPropsType.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#9 회원가입시 사용하는 버튼 컴포넌트 구현
  src/components/login/NextButton/NextButton.tsx
  src/components/login/NextButton/style.ts
  src/screens/RegisterNicknameScreen/RegisterNicknameScreen.tsx
  src/screens/RegisterPurposeScreen/RegisterPurposeScreen.tsx
  src/screens/RegisterRegionScreen/RegisterRegionScreen.tsx
  src/screens/RegisterWorkSpaceScreen/RegisterWorkSpaceScreen.tsx
  src/screens/ServiceTermScreen/ServiceTermScreen.tsx
Labels: ✨ Feature, 🔨 Refactor

#11 iOS 애플 로그인 구현
  ios/Podfile.lock
  ios/frontend.xcodeproj/project.pbxproj
  ios/frontend/Info.plist
  ios/frontend/frontend.entitlements
  package.json
  src/screens/OnboardingScreen/OnboardingScreen.tsx
  yarn.lock
Labels: ✨ Feature

#15 구글 로그인 구현
  babel.config.js
  ios/frontend/AppDelegate.mm
  package.json
  src/App.tsx
  src/screens/OnboardingScreen/OnboardingScreen.tsx
Labels: ✨ Feature, 🔨 Refactor

#16 Refactor/myscreennavigator
  .env
  android/app/src/main/AndroidManifest.xml
  env.d.ts
  package-lock.json
  src/components/mypage/EditProfileFeature/EditProfileFeature.tsx
  src/components/mypage/Header/Header.tsx
  src/components/mypage/Nickname/NickName.tsx
  src/components/mypage/ScrapButton/ScrapButton.tsx
  src/components/mypage/ScrapHeader/ScrapHeader.tsx
  src/data.js
  src/screens/EditProfileScreen/EditProfileScreen.tsx
  src/screens/MainNavigator.tsx
  src/screens/MainScreen.tsx
  src/screens/MemberCancellationCompleteScreen/MemberCancellationCompleteScreen.tsx
  src/screens/MemberCancellationScreen/MemberCancellationScreen.tsx
  src/screens/MyPageScreen/MyPageScreen.tsx
  src/screens/MyScreenNavigator.tsx
  src/screens/ScrapScreen/ScrapScreen.tsx
  src/screens/myScreenPropsType.ts
  yarn.lock
Labels: 🔨 Refactor

#17 애플 로그인, 구글 로그인 API 연동
  src/redux/service/AppleLogin.ts
  src/redux/service/GoogleLogin.ts
  src/redux/service/KakaoLogin.ts
  src/redux/slice/AppleLoginSlice.ts
  src/redux/slice/GoogleLoginSlice.ts
  src/redux/slice/KakaoLoginSlice.ts
  src/redux/store/store.ts
  src/screens/OnboardingScreen/OnboardingScreen.tsx
Labels: ✨ Feature, 📬 API

#18 회원가입 여부 확인, 회원 탈퇴 기능 구현
  src/redux/service/DeleteMember.ts
  src/redux/slice/DeleteMemberSlice.ts
  src/redux/store/store.ts
  src/screens/MemberCancellationScreen/MemberCancellationScreen.tsx
  src/screens/OnboardingScreen/OnboardingScreen.tsx
Labels: ✨ Feature, 📬 API

#19 닉네임 설정 관련 에러 출력
  src/redux/service/EditNicknameApi.ts
  src/redux/service/PostNicknameApi.ts
  src/redux/slice/MemberSlice.ts
  src/screens/EditProfileScreen/EditProfileScreen.tsx
  src/screens/RegisterNicknameScreen/RegisterNicknameScreen.tsx
Labels: ✨ Feature, 📬 API

#20 온보딩 화면 스타일 수정
  src/components/common/Wrapper.tsx
Labels: 🎨 Html&css

#21 Member API 변수명 변경
  src/redux/service/MemberApi.ts
Labels: 🐞 BugFix

#22 style: 마이 초기 화면 스타일 리팩토링
  src/components/mypage/Button/style.ts
  src/components/mypage/Nickname/NickName.tsx
  src/components/mypage/Nickname/style.ts
  src/components/mypage/ScrapButton/ScrapButton.tsx
  src/components/mypage/ScrapButton/style.ts
  src/screens/MyPageScreen/MyPageScreen.tsx
  src/screens/MyPageScreen/style.ts
Labels: 🎨 Html&css, 🔨 Refactor

#23 마이 페이지 스크랩 기능 추가 구현
  src/components/mypage/WorkSpaceList/WorkSpaceList.tsx
  src/screens/ScrapScreen/ScrapScreen.tsx
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#24 워크 스페이스 스타일 수정
  assets/images.ts
  assets/img/BookmarkYellow.png
  src/components/mypage/WorkSpaceList/style.ts
Labels: 🎨 Html&css

#25 회원 탈퇴 기능 수정
  src/redux/service/DeleteMember.ts
  src/screens/MemberCancellationScreen/MemberCancellationScreen.tsx
  src/screens/MemberCancellationScreen/RadioButton.tsx
  src/screens/MemberCancellationScreen/RadioGroup.tsx
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#26 마이페이지 버그 수정
  src/components/mypage/Nickname/NickName.tsx
  src/screens/EditProfileScreen/EditProfileScreen.tsx
Labels: 🐞 BugFix

#27 iOS 마이페이지 화면 SafeAreaView 설정
  src/components/common/MainHeader.tsx
  src/screens/MyPageScreen/style.ts
Labels: 🎨 Html&css

#28 온보딩 화면, 스크랩 화면 수정
  src/screens/OnboardingScreen/OnboardingScreen.tsx
  src/screens/ScrapScreen/ScrapScreen.tsx
Labels: 🔨 Refactor

#29 스크랩 한 워크스페이스가 없을 경우 출력되는 페이지 구현
  assets/images.ts
  assets/img/Sparkle.png
  src/screens/ScrapScreen/ScrapScreen.tsx
  src/screens/ScrapScreen/style.ts
Labels: ✨ Feature

#32 회원가입 후 홈스크린으로 이동시 발생하는 오류 해결
  src/screens/HomeScreen/HomeScreen.tsx
Labels: 🐞 BugFix

#33 style : 전반적인 마이 화면 스타일 수정
  src/components/login/Description/style.ts
  src/components/login/HeaderBackbutton/HeaderBackButton.tsx
  src/components/login/HeaderBackbutton/style.ts
  src/components/login/Title/style.ts
  src/components/mypage/EditProfileFeature/style.ts
  src/components/mypage/Header/style.ts
  src/components/mypage/ScrapHeader/ScrapHeader.tsx
  src/components/mypage/ScrapHeader/style.ts
  src/screens/EditProfileScreen/EditProfileScreen.tsx
  src/screens/EditProfileScreen/style.ts
  src/screens/HomeScreen/HomeScreen.tsx
  src/screens/MemberCancellationCompleteScreen/MemberCancellationCompleteScreen.tsx
  src/screens/MemberCancellationCompleteScreen/style.ts
  src/screens/MemberCancellationScreen/MemberCancellationScreen.tsx
  src/screens/MemberCancellationScreen/RadioButton.tsx
  src/screens/MemberCancellationScreen/style.ts
  src/screens/ScrapScreen/ScrapScreen.tsx
  src/screens/ScrapScreen/style.ts
Labels: 🎨 Html&css, 🔨 Refactor

#34 feat: 홈 화면 상세보기 페이지 기틀 마련
  assets/images.ts
  assets/img/blackLogo.png
  assets/img/grayLogo.png
  src/redux/service/GetDetailWorkspaceApi.ts
  src/redux/slice/GetDetailWorkspaceSlice.ts
  src/redux/slice/WorkspaceListByRegionSlice.ts
  src/redux/store/store.ts
  src/screens/EditProfileScreen/style.ts
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeDetailScreen/style.ts
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
  src/screens/HomeScreen/HomeMainScreen/HomeScrollDetail.tsx
  src/screens/HomeScreen/HomeMainScreen/style.ts
  src/screens/HomeScreen/filter/filterFunc.ts
  src/screens/HomeScreenNavigator.tsx
  src/screens/MainNavigator.tsx
  src/screens/homeScreenPropsType.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🔨 Refactor

#35 fix: 이미지, 위도 및 경도 1번 API에서 GET
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeDetailScreen/style.ts
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
  src/screens/HomeScreen/HomeMainScreen/HomeScrollDetail.tsx
  src/screens/homeScreenPropsType.ts
Labels: 🐞 BugFix

#36 상세 페이지 스크랩 기능 구현
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeDetailScreen/style.ts
Labels: ✨ Feature, 🐞 BugFix

#37 스크랩 스타일 수정
  src/components/mypage/WorkSpaceList/style.ts
  src/screens/HomeScreen/HomeDetailScreen/style.ts
  src/screens/ScrapScreen/ScrapScreen.tsx
  src/screens/ScrapScreen/style.ts
Labels: 🎨 Html&css

#39 멤버 온보딩 상태에 따른 페이지 이동
  src/redux/service/Onboarding.ts
  src/redux/slice/OnboardingSlice.ts
  src/redux/store/store.ts
  src/screens/OnboardingScreen/OnboardingScreen.tsx
Labels: ✨ Feature, 📬 API

#40 스크랩 페이지 스크롤뷰 적용
  src/screens/ScrapScreen/ScrapScreen.tsx
Labels: 🎨 Html&css

#42 앱 아이콘 설정
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/1024.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/120 1.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/120.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/180.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/40.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/58.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/60.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/80.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/87.png
  ios/frontend/Images.xcassets/AppIcon.appiconset/Contents.json
Labels: 🎨 Html&css

#43 스플래시 스크린 구현
  android/app/build.gradle
  android/app/src/main/java/com/frontend/MainActivity.java
  android/app/src/main/res/drawable/launch_screen.png
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/settings.gradle
  ios/LaunchScreen.storyboard
  ios/frontend/Images.xcassets/Contents.json
  ios/frontend/Images.xcassets/splash.imageset/Contents.json
  ios/frontend/Images.xcassets/splash.imageset/launch_screen.png
  package.json
  src/App.tsx
Labels: ✨ Feature, 🎨 Html&css

#44 매거진 메인 페이지 구현
  src/components/common/SubHeader.tsx
  src/redux/service/Magazine.ts
  src/redux/slice/MagazineSlice.ts
  src/redux/store/store.ts
  src/screens/MagazineScreen/MagazineScreen.tsx
Labels: ✨ Feature, 🎨 Html&css

#45 회원가입 시 이용 약관 URL 연결
  src/data.js
  src/screens/ServiceTermScreen/ServiceTerm.tsx
  src/screens/ServiceTermScreen/ServiceTermScreen.tsx
Labels: ✨ Feature

#46 feat: 홈 화면 지역별 필터링 추가
  package-lock.json
  src/components/mypage/ScrapHeader/style.ts
  src/redux/slice/GetDetailWorkspaceSlice.ts
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
  yarn.lock
Labels: ✨ Feature

#47 마이 페이지 이용 약관 URL 연동
  src/screens/MyPageScreen/MyPageScreen.tsx
  src/screens/MyScreenNavigator.tsx
  src/screens/MyServiceTermScreen/MyServiceTermScreen.tsx
  src/screens/myScreenPropsType.ts
Labels: ✨ Feature

#49 style: 스크랩 버튼 스타일 수정
  src/components/mypage/WorkSpaceList/WorkSpaceList.tsx
  src/components/mypage/WorkSpaceList/style.ts
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeDetailScreen/style.ts
Labels: 🎨 Html&css

#50 refactor: 매거진 네비게이터 추가
  src/components/common/SubHeader.tsx
  src/screens/MagazineScreen/MagazineDetailScreen/MagazineDetailScreen.tsx
  src/screens/MagazineScreen/MagazineMainScreen/MagazineMainScreen.tsx
  src/screens/MagazineScreenNavigator.tsx
  src/screens/MainNavigator.tsx
  src/screens/magazineScreenPropsType.ts
Labels: 🔨 Refactor

#53 마이페이지 이용 방법 컴포넌트 추가, 헤더 변경
  src/components/mypage/Button/Button.tsx
  src/data.js
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
  src/screens/MyPageScreen/MyPageScreen.tsx
  src/screens/MyPageScreen/style.ts
Labels: 🎨 Html&css

#54 매거진 내용 이미지 이슈로 인한 매거진 텍스트 작성
  src/screens/MagazineScreen/MagazineDetailScreen/MagazineDetailScreen.tsx
  src/screens/MagazineScreen/MagazineDetailScreen/style.ts
  src/screens/MagazineScreen/MagazineMainScreen/MagazineMainScreen.tsx
  src/screens/MagazineScreen/MagazineMainScreen/style.ts
Labels: 🐞 BugFix

#55 매거진 이미지 임시 추가
  assets/images.ts
  assets/img/magazine_1.png
  assets/img/magazine_2.png
  assets/img/magazine_3.png
  assets/img/magazine_4.png
  assets/img/magazine_5.png
  assets/img/magazine_6.png
Labels: 🎨 Html&css

#57 마이페이지 스타일 수정
  src/components/mypage/WorkSpaceList/style.ts
  src/screens/MemberCancellationScreen/style.ts
Labels: 🎨 Html&css

#58 style: 스크랩 버튼 조정
  src/screens/HomeScreen/HomeDetailScreen/style.ts
Labels: 🎨 Html&css

#59 fix: 매거진 화면 버그 해결
  src/components/mypage/WorkSpaceList/style.ts
  src/redux/service/Magazine.ts
  src/screens/MagazineScreen/MagazineDetailScreen/MagazineDetailScreen.tsx
  src/screens/MagazineScreen/MagazineDetailScreen/style.ts
  src/screens/MagazineScreen/MagazineMainScreen/MagazineMainScreen.tsx
  src/screens/MagazineScreen/MagazineMainScreen/style.ts
Labels: 🎨 Html&css, 🐞 BugFix

#60 온보딩 상태에 따라 페이지 이동하는 부분 수정, 회원 탈퇴 수정
  src/redux/service/DeleteMember.ts
  src/screens/MemberCancellationCompleteScreen/MemberCancellationCompleteScreen.tsx
  src/screens/OnboardingScreen/OnboardingScreen.tsx
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix

#61 로그아웃 할 경우 AsyncStorage 초기화
  src/redux/service/Logout.ts
Labels: 🐞 BugFix

#62 내비게이터 깨지는 아이콘 변경
  assets/img/HomeIcon.png
  assets/img/MagazineIcon.png
  src/screens/MainNavigator.tsx
Labels: 🎨 Html&css

#63 로그아웃 내비게이터 변경
  src/screens/EditProfileScreen/EditProfileScreen.tsx
Labels: 🐞 BugFix

#64 feat: 협찬 업체에 대한 컨텐츠 추가
  assets/images.ts
  assets/img/sponsor_1st_image.png
  assets/img/sponsor_2nd_image.png
  src/data.js
  src/screens/EditProfileScreen/style.ts
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeDetailScreen/style.ts
  src/screens/RegisterNicknameScreen/style.ts
  src/screens/RegisterRegionScreen/RegisterRegionScreen.tsx
  src/screens/ScrapDetailScreen/ScrapDetailScreen.tsx
  src/screens/ScrapDetailScreen/style.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#65 fix: 버그들 해결
  package.json
  src/components/mypage/WorkSpaceList/WorkSpaceList.tsx
  src/components/mypage/WorkSpaceList/style.ts
  src/screens/HomeScreen/HomeDetailScreen/style.ts
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
  src/screens/HomeScreen/HomeMainScreen/HomeScrollDetail.tsx
  src/screens/MemberCancellationScreen/MemberCancellationScreen.tsx
  yarn.lock
Labels: 🎨 Html&css, 🐞 BugFix

#66 fix: 지역 설정 설명 줄바꿈 깔끔히 수정
  src/screens/RegisterRegionScreen/RegisterRegionScreen.tsx
Labels: 🎨 Html&css

#67 console.log 삭제
  src/redux/service/EditNicknameApi.ts
  src/screens/OnboardingScreen/OnboardingScreen.tsx
Labels: 🔨 Refactor

#68 fix: 홈 화면 위도 경도 세팅 수정
  src/data.js
Labels: 🔨 Refactor

#69 style: 태그 줄 바꿈 설정
  src/redux/service/DeleteMember.ts
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeDetailScreen/style.ts
  src/screens/RegisterNicknameScreen/RegisterNicknameScreen.tsx
  src/screens/ScrapDetailScreen/ScrapDetailScreen.tsx
  src/screens/ScrapDetailScreen/style.ts
Labels: 🎨 Html&css

#70 프로필 편집 아이콘 삭제
  src/screens/EditProfileScreen/EditProfileScreen.tsx
  src/screens/EditProfileScreen/style.ts
Labels: 🎨 Html&css

#71 fix: 패키지명 변경
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/debug/java/workus_mayonnaise/application/ReactNativeFlipper.java
  android/app/src/main/java/workus_mayonnaise/application/MainActivity.java
  android/app/src/main/java/workus_mayonnaise/application/MainApplication.java
  android/app/src/main/res/drawable/launch_screen.jpg
  android/app/src/main/res/drawable/launch_screen.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.jpg
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.jpg
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.jpg
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.jpg
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.jpg
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.jpg
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.jpg
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.jpg
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.jpg
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.jpg
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/hs_err_pid25580.log
Labels: 🌏 Deploy, ⚙ Setting

#72 Fix/change package name
  android/app/build.gradle
  android/app/src/release/java/com/frontend/ReactNativeFlipper.java
  android/app/src/release/java/workus_mayonnaise/application/ReactNativeFlipper.java
Labels: 🌏 Deploy

#73 스타일 변경
  assets/img/logo_black.png
  assets/img/logo_white.png
  src/screens/MagazineScreen/MagazineDetailScreen/style.ts
Labels: 🎨 Html&css

#75 닉네임 유효성 검사 기능 구현
  src/redux/service/ValidationName.ts
  src/redux/slice/ValidationNameSlice.ts
  src/redux/store/store.ts
  src/screens/RegisterNicknameScreen/RegisterNicknameScreen.tsx
Labels: ✨ Feature

#76 지도 마커 이미지 사이즈 설정
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
Labels: 🐞 BugFix

#80 fix: google-services.json과 build.gradle 수정
  android/app/build.gradle
  android/app/google-services.json
Labels: 🌏 Deploy

#81 비회원 시나리오 구현
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
  src/screens/MyPageScreen/MyPageScreen.tsx
  src/screens/OnboardingScreen/OnboardingScreen.tsx
Labels: ✨ Feature

#82 지역 설정 기능 구현
  src/components/login/RegisterButton/RegisterButton.tsx
  src/redux/service/PostRegionApi.ts
  src/screens/MyScreenNavigator.tsx
  src/screens/RegionSettingScreen.tsx
  src/screens/myScreenPropsType.ts
Labels: ✨ Feature

#84 지역 설정 관련 수정
  src/screens/HomeScreen/HomeMainScreen/HomeScreen.tsx
  src/screens/RegionSettingScreen.tsx
Labels: 🐞 BugFix

#85 로그인 유지 기능 구현
  src/App.tsx
  src/redux/service/Logout.ts
  src/screens/EditProfileScreen/EditProfileScreen.tsx
Labels: ✨ Feature, 🐞 BugFix

#87 로그인 유지 기능 수정
  src/App.tsx
  src/screens/EditProfileScreen/EditProfileScreen.tsx
Labels: 🐞 BugFix

#88 중복 dispatch 삭제
  src/components/mypage/EditProfileFeature/EditProfileFeature.tsx
Labels: 🐞 BugFix

#89 지도 아이콘 크기 설정
  src/screens/HomeScreen/HomeDetailScreen/HomeDetailScreen.tsx
  src/screens/ScrapDetailScreen/ScrapDetailScreen.tsx
Labels: 🎨 Html&css
